### ISSUE TITLE
Protocol "https:" not supported. Expected "http:"

### ISSUE THREAD

**Issue by vczb** [vczb/lighthouse-reporter#34]
This error occur when dispatch a report

```
  LH:status Generating results... +3ms
Report is done for https://vczb.github.io/about
Report finished
Report data:
 [
  {
    url: 'https://vczb.github.io/',
    accessibility: 81,
    best: 92,
    performance: 76,
    pwa: 30,
    seo: 98
  },
  {
    url: 'https://vczb.github.io/about',
    accessibility: 71,
    best: 92,
    performance: 67,
    pwa: 20,
    seo: 97
  }
]
TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
    at new NodeError (node:internal/errors:371:5)
    at new ClientRequest (node:_http_client:158:11)
    at Object.request (node:http:96:10)
    at /home/vini/src/lighthouse-reporter/src/app/controllers/trigger.controller.ts:111:28
    at step (/home/vini/src/lighthouse-reporter/src/app/controllers/trigger.controller.ts:33:23)
    at Object.next (/home/vini/src/lighthouse-reporter/src/app/controllers/trigger.controller.ts:14:53)
    at fulfilled (/home/vini/src/lighthouse-reporter/src/app/controllers/trigger.controller.ts:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_INVALID_PROTOCOL'
}
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by vczb** [comment]
closed by #37
